language: generic

# bails on stock trusty due to https://llvm.org/bugs/show_bug.cgi?id=18402

matrix:
  include:
    - os: linux
      sudo: false
      dist: precise
      env: HEADERS="default precise"
    - os: linux
      sudo: required
      dist: trusty
      env: HEADERS="default trusty"
    - os: linux
      sudo: false
      dist: precise
      env: HEADERS="libstdc++-4.8-dev upgrade on precise"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-4.8-dev' ]
    - os: linux
      sudo: false
      dist: precise
      env: HEADERS="libstdc++-4.9-dev upgrade on precise"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-4.9-dev' ]
    - os: linux
      sudo: false
      dist: precise
      env: HEADERS="libstdc++-5-dev upgrade on precise"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]

script:
  ./test.sh